---
eda_decision_environments:
  - name: PhilFooDE
    description: DE created using infra.eda_configuration collection
    image_url: "brew.registry.redhat.io/rh-osbs/ansible-automation-platform-25-de-supported-rhel8:latest"
