---
controller_hosts:
 - name: another_host1
   inventory: Demo Inventory2
   variables:
     ansible_connection: local
     ansible_python_interpreter: '{{ ansible_playbook_python }}'
 - name: another_host2
   inventory: Demo Inventory2
...
